
export const dynamic = 'force-dynamic';
import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { SidebarProvider } from '~/context/SidebarContext';
import { UserProvider } from "~/context/UserProvider";

export const metadata: Metadata = {
  title: "Dashboard App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <SidebarProvider>
          <TRPCReactProvider>
            <UserProvider>
              {children}
            </UserProvider>
          </TRPCReactProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
